### ISSUE TITLE
Select Grant Application direct in Editor tool #44

### ISSUE THREAD

**Issue by cidarm** [SFDO-Community/GrantGuides#132]
OVERVIEW
Choose a Grant application to work on in the editor. Feature to switch existing Grants directly in same page

ACCEPTANCE CRITERIA
User can see the list of available Grants and can select a grant application in the editor, switching active Grant.

OUT OF SCOPE

BACKGROUND/REFERENCE
Simple solution may be to adda dropdown list on Editor page with available grants and let user choose and switch grants. This maybe bad UX if ORG has many grants list will be large and require some filters. Search as Modal dialog where to search and filter what grant to use.

**Comment by marycrow** [comment]
I'd like to revist this - it may make more sense to move the Grant Editor tab on the other side of the Grant Application tab to reinforce the process priority on moving from Application to application.

**Comment by marycrow** [comment]
completed as requested
