### ISSUE TITLE
Launch Grant Editor from Grant Application

### ISSUE THREAD

**Issue by marycrow** [SFDO-Community/GrantGuides#134]
**OVERVIEW**

A grant application from a year ago needs to be located and edited for the upcoming application submission. A user can find it under the Grant Application tab but it's not intuitive how to launch the editor from there. The specific grant might not show on the home tab due to it's age.

**ACCEPTANCE CRITERIA**
Be able to launch the editor from the Grant Application record

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**
<img width="1197" alt="Screenshot 2024-02-07 at 8 51 03 AM" src="https://github.com/SFDO-Community/GrantGuides/assets/35714113/8d876694-8450-4cd9-a24f-995d2e1ff799">

**Comment by iandrosov** [comment]
@marycrow This is existing feature, need to review this issue

**Comment by cidarm** [comment]
Clean repo Flexipages.  /force-app/main/flexipages.

1 per page.

**Comment by cidarm** [comment]
Modified the Grant Application Lightning Page to include the Edit Application, Edit, and Preview buttons.

<img width="1443" alt="Screenshot 2024-02-17 at 5 03 11 PM" src="https://github.com/SFDO-Community/GrantGuides/assets/1333788/e8beb94d-d0fc-4ef5-bc1e-b0a2c4ef9ca0">

**Comment by Aburrows2023** [comment]
![Image](https://github.com/SFDO-Community/GrantGuides/assets/146023721/242e4da5-a6aa-4720-93bf-d84d2857c49e)

This looks resolved to me!
