### ISSUE TITLE
Add Sections via the Grant Editor

### ISSUE THREAD

**Issue by marycrow** [SFDO-Community/GrantGuides#135]
**OVERVIEW**
As a user I may create a grant application record in advance for tracking and then later want to add the sections.

**ACCEPTANCE CRITERIA**
Be able to add sections from the Grant Editor at the start of Application

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**
<img width="1217" alt="Screenshot 2024-02-07 at 9 32 27 AM" src="https://github.com/SFDO-Community/GrantGuides/assets/35714113/ae6a1ca5-0d8a-42d2-bbed-6e09ddb3da0c">

**Comment by iandrosov** [comment]
Rename [Reorder] button to more clear name Manage Sections. Feature allows to add new or reorder existing sections
![Screenshot 2024-02-14 at 16 38 38](https://github.com/SFDO-Community/GrantGuides/assets/1155013/210a8453-4a4a-455f-848a-1d24a79a16b6)

**Comment by marycrow** [comment]
Verified in the Dev org that the label on the button now says Manage Sections
