### ISSUE TITLE
Link Grant Application to Opportunity

### ISSUE THREAD

**Issue by iandrosov** [SFDO-Community/GrantGuides#49]
**OVERVIEW**
Grants is thought to be started or created as Opportunity for some funding collection with amount and other details.
Add Opportunity lookup field to Grants Application record
Create Formula fields cross object to bring related information to Grant App
Account Name
Amount

**ACCEPTANCE CRITERIA**
View Opportunity and related data because Grant does not exist in a vacuum

**OUT OF SCOPE**
Create new Opportunity from Grant
Automate Opportunity creation

**BACKGROUND/REFERENCE**

**Comment by marycrow** [comment]
This was also requested/confirmed needed by nonprofit user during Sprint '23

**Comment by marycrow** [comment]
Prioritizing as a Documentation update only and for any object....and not an enhancement of the app

**Comment by marycrow** [comment]
@Abundezt  - Please review the setup documentation/WIKI for this addition and if not found please add it.

**Comment by Abundezt** [comment]
@marycrow @iandrosov Updated the wiki https://github.com/SFDO-Community/GrantGuides/wiki#customizing-the-grants-content-kit

Let me know if anything needs to be changed.
