### ISSUE TITLE
Add Samples of Content blocks to sample data

### ISSUE THREAD

**Issue by iandrosov** [SFDO-Community/GrantGuides#73]
**OVERVIEW**
Current initialize sample data inserts Sections, this feature to add related text content blocks as sample data to initialize new package install.

**ACCEPTANCE CRITERIA**
As part of new install data is initialized with set of sections and related text content blocks.

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**

**Comment by marycrow** [comment]
New sample content was added to the trial org for Sprint '23. A copy of the content is attached below. The org will expire on April 28th. Org URL: https://clientcloudcare6.lightning.force.com/

[GCK_content.zip](https://github.com/Salesforce-org-Impact-Labs/GrantGuides/files/11115275/GCK_content.zip)
