### ISSUE TITLE
Swap order of sections: Plan of Action to come after Goals and Objectives

### ISSUE THREAD

**Issue by kelkoh** [SFDO-Community/GrantGuides#89]
**OVERVIEW**
This is a UI Enhancement request.
Working with a grant writer it was suggested that typically the Goals and Objectives section would come before the Plan of Action. 

**ACCEPTANCE CRITERIA**

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**

![Screenshot 2023-03-30 120200](https://user-images.githubusercontent.com/113560681/228938245-65d28323-5fdd-46e5-b91f-80bf79fd0975.png)

**Comment by marycrow** [comment]
Confirmed update made to Ui
