### ISSUE TITLE
Grant Editor Tab

### ISSUE THREAD

**Issue by marycrow** [SFDO-Community/GrantGuides#92]
**OVERVIEW**
UI Enhancement - The Grant Editor tab right next to the first tab makes selecting which grant to edit confusing.

Along with that thought, having the Applications In Progress component higher on the left and moving the Grant launch wizard to the right above the donut chart might help with the confusion.

**ACCEPTANCE CRITERIA**

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**

**Comment by cidarm** [comment]
Document as a known issue.

**Comment by iandrosov** [comment]
Add Create New Grant UI component to Editor

![Image](https://github.com/SFDO-Community/GrantGuides/assets/1155013/4eea5286-e9dc-44f3-bedb-a4a990974303)

**Comment by marycrow** [comment]
For review at the next meeting - The added UI is great at the start, but it may be better for ongoing use to have a button similar to the Ai button in the same area above to start a new grant.
