### ISSUE TITLE
Chatter

### ISSUE THREAD

**Issue by marycrow** [SFDO-Community/GrantGuides#93]
**OVERVIEW**
UI Enhancement - Page layout updates
- Chatter should be enabled and included in the page layout of the grant record. 
- Add Path for Status
- We were not able to add the Topics to the page layout in the trial

**ACCEPTANCE CRITERIA**

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**

**Comment by marycrow** [comment]
@Abundezt -  Please review the WIKI documentation to ensure that the above information has been added when going through setup.

**Comment by Abundezt** [comment]
@marycrow @iandrosov Wiki has been updated with the above settings
https://github.com/SFDO-Community/GrantGuides/wiki#configure-essential-settings-and-features

Let me know if anything needs to be changed.
